myapp/urls.py
from django.urls import path
from myapp import views
from myapp.views import ResetPasswordView
from django.contrib.auth import views as auth_views

app_name = 'myapp'

urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'login/', views.user_login, name='login'),
    path(r'logout/', views.user_logout, name='logout'),
    path(r'register/', views.user_register, name='register'),
    path(r'password-reset/', ResetPasswordView.as_view(), name='password_reset'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='myapp/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='myapp/password_reset_complete.html'),
         name='password_reset_complete'),

    path(r'about/', views.about, name='about'),
    path(r'<int:cat_no>/', views.detail, name='detail'),
    path(r'products/', views.products, name='products'),
    path(r'place_order/', views.place_order, name='placeOrder'),
    path(r'products/<int:prod_id>/', views.productdetail, name='productDetail'),
    path(r'orders/', views.myorders, name='orders'),
    path(r'profile/', views.profile, name='users-profile'),

    # path(r"password_change", views.password_change, name="password_change")
]

mysiteF22/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from PIL import Image
from django.utils import timezone


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200)
    warehouse = models.CharField(max_length=200, default='Windsor')

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=100, validators=[MinValueValidator(0), MaxValueValidator(1000)])
    available = models.BooleanField(default=True)
    interested = models.PositiveIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)

    def __str__(self):
        return self.name

    def refill(self):
        self.stock += 100
        self.save()


class Client(User):
    PROVINCE_CHOICES = [('AB', 'Alberta'), ('MB', 'Manitoba'), ('ON', 'Ontario'), ('QC', 'Quebec'), ]
    company = models.CharField(max_length=50, blank=True)
    shipping_address = models.CharField(max_length=300, null=True, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province = models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    interested_in = models.ManyToManyField(Category)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    class Meta:
        verbose_name = "Client"


class Order(models.Model):
    ORDER_STATUS = [(0, 'Order Cancelled'), (1, 'Order Placed'), (2, 'Order Shipped'), (3, 'Order Delivered')]
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    num_units = models.PositiveIntegerField(default=1)
    order_status = models.IntegerField(default=1, choices=ORDER_STATUS)
    status_date = models.DateField(auto_now=True)

    def __str__(self):
        return self.product.__str__() + ' -- ' + self.client.__str__()

    def total_cost(self):
        """ Total cost for all items in the order """
        return self.product.price * self.num_units


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='default.jpg', upload_to='profile_images')
    bio = models.TextField()

    def __str__(self):
        return self.user.username

    # resizing images
    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 100 or img.width > 100:
            new_img = (100, 100)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from myapp.models import Order, Client, Profile
from django.contrib.auth.models import User


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('client', 'product', 'num_units')

        widgets = {
            'client': forms.RadioSelect(),
        }

        labels = {
            'num_units': 'Quantity',
            'client': 'Client Name',
        }


class InterestForm(forms.Form):
    # interested = forms.CharField(widget=forms.RadioSelect)
    interested = forms.ChoiceField(choices=[(1, 'Yes'), (0, 'No')], widget=forms.RadioSelect)
    quantity = forms.IntegerField(min_value=1)
    comments = forms.CharField(required=False, widget=forms.Textarea, label='Additional Comments')


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    username = forms.CharField(max_length=100, required=True)
    password1 = forms.CharField(max_length=50, required=True, widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50, required=True, widget=forms.PasswordInput())
    email = forms.EmailField(required=True)

    class Meta:
        model = Client
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")

class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email']


class UpdateProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}))

    class Meta:
        model = Profile
        fields = ['avatar', 'bio']

myapp/views.py
from datetime import datetime
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .models import Category, Product, Client, Order
from .forms import OrderForm, InterestForm, RegisterForm, UpdateUserForm, UpdateProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


# Create your views here.

def user_register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect("myapp:login")
        else:
            print('form invalid')
    else:
        form = RegisterForm()
    return render(request=request, template_name="myapp/register.html", context={"register_form": form})


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                cur_datetime = datetime.now()
                request.session['last_login'] = str(cur_datetime)
                request.session.set_expiry(3600)
                return HttpResponseRedirect(reverse('myapp:orders'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('myapp:login'))


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'myapp/password_reset.html'
    email_template_name = 'myapp/password_reset_email.html'
    subject_template_name = 'myapp/password_reset_subject'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('myapp:login')


def index(request):
    cat_list = Category.objects.all().order_by('id')[:10]
    msg = ""
    last_login = "your logged out"
    # print(request.user)
    if request.session.get('last_login', False):
        last_login = datetime.strptime(request.session.get('last_login').split(".")[0], '%Y-%m-%d %H:%M:%S')
        # print(last_login, type(last_login))
        # sleep(2)
        # print(datetime.now(), type(datetime.now()))
        time = datetime.now() - last_login
        if time.total_seconds() > 3600:
            msg = "Your last login was more than one hour ago"
            logout(request)
        # last_login = request.session.get('last_login')
        # login_flag = True
    # else:
    #     last_login = "Your last login was more than one hour ago"
    #     login_flag = False
    context = {
        'cat_list': cat_list,
        'last_login': last_login,
        'user': request.user,
        'msg': msg
    }
    return render(request, 'myapp/index.html', context=context)


def about(request):
    if 'about_visits' in request.COOKIES:
        count_visited = int(request.COOKIES['about_visits'])
        count_visited += 1
    else:
        count_visited = 1
    response = render(request, 'myapp/about.html', {'no_of_times_visited': count_visited})
    response.set_cookie('about_visits', count_visited, max_age=300)
    return response


def detail(request, cat_no):
    category = get_object_or_404(Category, pk=cat_no)
    products = Product.objects.filter(category=category)
    # return render(request, 'myapp/detail0.html', {'category': category, 'products': products})
    return render(request, 'myapp/detail.html', {'category': category, 'products': products})


def products(request):
    prodlist = Product.objects.all().order_by('id')[:10]
    return render(request, 'myapp/products.html', {'prodlist': prodlist})


@login_required
def place_order(request):
    msg = ''
    prodlist = Product.objects.all()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            product_name = form.cleaned_data['product']
            order = form.save(commit=False)
            if order.num_units <= order.product.stock:
                order.save()
                product = Product.objects.get(name=product_name)
                product.stock = product.stock - order.num_units
                product.save()
                msg = 'Your order has been placed successfully.'
            else:
                msg = 'We do not have sufficient stock to fill your order !!!'
                return render(request, 'myapp/order_response.html', {'msg': msg})
    else:
        form = OrderForm()
    return render(request, 'myapp/placeorder.html', {'form': form, 'msg': msg, 'prodlist': prodlist})


@login_required
def productdetail(request, prod_id):
    try:
        msg = ''
        product = Product.objects.get(id=prod_id)
        # product = get_object_or_404(Product, pk=prod_id)
        if request.method == 'GET':
            form = InterestForm()
        elif request.method == 'POST':
            form = InterestForm(request.POST)
            if form.is_valid():
                interested = form.cleaned_data['interested']
                print("Interested: ", interested)
                if int(interested) == 1:
                    product.interested += 1
                    product.save()
                    print('form is valid')
                    return redirect(reverse('myapp:index'))
        # else:
        #     form = InterestForm()
        return render(request, 'myapp/productdetail.html', {'form': form, 'msg': msg, 'product': product})
    except Product.DoesNotExist:
        msg = 'The requested product does not exist. Please provide correct product id !!!'
        return render(request, 'myapp/productdetail.html', {'msg': msg})


def myorders(request):
    try:
        user = request.user
        if not user.is_authenticated:
            return redirect('myapp:login')
        client = Client.objects.get(username=user.username)
        orders = Order.objects.filter(client=client)
        distinct_orders = []
        for order in orders:
            print(order.product.name)
            if order.product.name not in distinct_orders:
                distinct_orders.append(order.product.name)
        msg = f'Orders placed by {client} :-'
        if orders.count() == 0:
            msg = f'{client} has not placed any orders'
        return render(request, 'myapp/myorders.html', {'orders': distinct_orders, 'msg': msg})
    except Client.DoesNotExist:
        msg = 'You are not a registered client'
        return render(request, 'myapp/myorders.html', {'msg': msg})


@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)
        print(profile_form)
        print(request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            # messages.success(request, 'Your profile is updated successfully')
            return redirect('myapp:users-profile')
        else:
            print("invalid")
    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)

    return render(request, 'myapp/profile.html', {'user_form': user_form, 'profile_form': profile_form})

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}
{% block title %}About{% endblock %}
{#{% block myhdg %} Hello {{ user }} {% endblock %}#}
{% block body_block %}
    <h3>This is an Online Store App</h3>
    {% if no_of_times_visited %}
        <p>Number of times this page visited - {{ no_of_times_visited }}</p>
    {% endif %}
    {#    <p><a href="{% url 'myapp:index' %}">Index page using URL namespacing</a></p>#}
    {#    <p><a href="/myapp/">Index page using hardcoded URL</a></p>#}
{% endblock %}

myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
    <h3>This is an Online Store App</h3>
    <p><a href="{% url 'myapp:index' %}">Index page using URL namespacing</a></p>
    <p><a href="/myapp/">Index page using hardcoded URL</a></p>
</body>
</html>

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}"/>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Online Store APP - {% block title %}Welcome!{% endblock %}</title>
</head>
<body>
<div>
    <h1>{% block myhdg %}
        {% if user.is_authenticated %}
            Hello {{ user.first_name }}
        {% else %}
            Hello The-Four
        {% endif %}
    {% endblock %}</h1>
    {% block body_block %}*** {% endblock %}
</div>
<hr/>
<div>
    <ul>
        {% block link_block %}
            <li class="hbar1"><a href="/myapp/about/">Find out about this
                site</a></li>
            <li class="hbar1"><a href="{% url 'myapp:products' %}">Click here to
                see products</a></li>
            {% if user.is_authenticated %}
                <li class="hbar1"><a href="{% url 'myapp:logout' %}">Logout</a></li>
                <li class="hbar1"><a href="{% url 'myapp:orders' %}">Products Ordered</a></li>
            {% else %}
                <li class="hbar1"><a href="{% url 'myapp:login' %}">Login</a></li>
                <li class="hbar1"><a href="{% url 'myapp:register' %}">Register</a></li>
            {% endif %}
            <li class="hbar1"><a href="{% url 'myapp:index' %}">Click here to
                return to main page</a><br/></li>
        {% endblock %}
    </ul>
</div>
</body>
</html>

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block title %}Detail{% endblock %}
{#{% block myhdg %} Hello The-Four {% endblock %}#}
{% block body_block %}
    {% if category %}
        <h4>Category Name - {{ category.name }}</h4>
        <h4>Category Warehouse - {{ category.warehouse }}</h4>
        <h3>List of products for the {{ category.name }} category</h3>
        <ol>
            {% for product in products %}
                <li> {{ product.name }} </li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available categories!</strong>
    {% endif %}
{#    <p><a href="{% url 'myapp:index' %}">Index page</a></p>#}
{% endblock %}

myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail page</title>
</head>
<body>
{% if category %}
    <h3>Category Name - {{ category.name }}</h3>
    <h4>Category Warehouse - {{ category.warehouse }}</h4>
    <h4>List of products for the {{ category.name }} category</h4>
    <ol>
        {% for product in products %}
            <li> {{ product.name }} </li>
        {% endfor %}
    </ol>
{% else %}
    <strong>There are no available categories!</strong>
{% endif %}
<p><a href="{% url 'myapp:index' %}">Index page</a></p>
</body>
</html>

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{#{% block myhdg %}#}
{# Hello {{ user }}#}
{#{% endblock %}#}
{% block body_block %}
{% if user.is_active %}
<div class="row my-3 p-3">
    <img class="rounded-circle account-img" src="{{ user.profile.avatar.url }} " style="cursor: pointer;" />
</div>
<p>Last Login - {{ last_login }}</p>
{% if cat_list %}
<h3>List of Categories</h3>
<ol>
    {% for cat in cat_list %}
    <li><a href="{{ cat.id }}/">{{ cat.name }}</a></li>
    {% endfor %}
</ol>
{% else %}
<strong>There are no available categories!</strong>
{% endif %}
{% else %}
{{ msg }}
{% endif %}
{# <p><a href="{% url 'myapp:about' %}">About page</a></p>#}
{% endblock %}
{% block link_block %}
<li class="hbar1"><a href="/myapp/about/">Find out about this
        site</a></li>
<li class="hbar1"><a href="{% url 'myapp:products' %}">Click here to
        see products</a></li>
{% if user.is_authenticated %}
<li class="hbar1"><a href="{% url 'myapp:logout' %}">Logout</a></li>
<li class="hbar1"><a href="{% url 'myapp:users-profile' %}">Upload Profile</a></li>
{% else %}
<li class="hbar1"><a href="{% url 'myapp:login' %}">Login</a></li>
{% endif %}
<li class="hbar1"><a href="{% url 'myapp:orders' %}">Products Ordered</a></li><br />
{% endblock link_block %}

myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}
{% block title %}Detail{% endblock %}
{#{% block myhdg %} Hello The-Four {% endblock %}#}
{% block body_block %}
    {% if msg %}
       <h3>{{ msg }}</h3>
    {% endif %}
{% endblock %}

myapp/templates/myapp/password_reset.html
{% extends "myapp/base.html" %}
{% block body_block %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <div id="error_div"></div>
                            <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group">
                                            <label class="small mb-1" for="id_email">Email</label>
                                            <input type="email" name="email" class="form-control"
                                                   autocomplete="email" maxlength="254" required id="id_email"
                                                   placeholder="Enter email">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group mt-0 mb-1">
                                            <button type="submit" class="col-md-12 btn btn-dark">Submit
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'myapp:register' %}">Create A New Account</a><br><br>
                                <a href="{% url 'myapp:login' %}">Back To Login</a><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock body_block %}

myapp/templates/myapp/password_reset_complete.html
{% extends "myapp/base.html" %}
{% block content %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Your password has been set. You may go ahead and <a href="{% url 'login' %}">Login Here</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

myapp/templates/myapp/placeorder.html
{% extends 'myapp/base.html' %}
{% block title %}PlaceOrder{% endblock %}
{#{% block myhdg %} Hello The-Four {% endblock %}#}
{% block body_block %}
    {% if prodlist %}
        <h3>List of products</h3>
        <ol>
            {% for product in prodlist %}
                {% if product.available %}
                    <li> {{ product.name }} </li>
                {% endif %}
            {% endfor %}
        </ol>

        <div class = "form-group">
        <h3 style = "text-align: left;">Order form</h3>
        <form method = "POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type = "submit" class = "btn btn-primary">Place Order</button>
        </form>

        {% if msg %}
            <p>{{ msg }}</p>
        {% endif %}

    {% else %}
        <strong>There are no available products!</strong>
    {% endif %}
{#    <p><a href="{% url 'myapp:index' %}">Index page</a></p>#}
{% endblock %}

myapp/templates/myapp/productdetail.html
{% extends 'myapp/base.html' %}
{% block title %}Product Detail{% endblock %}
{#{% block myhdg %} Hello The-Four {% endblock %}#}
{% block body_block %}
    {% if product %}
        <h3>Product Name - {{ product.name }}</h3>
        <p>Number of people interested in - {{ product.interested }}</p>
        <p>Price of the product - {{ product.price }}</p>

        <div class="form-group">
        <h3 style="text-align: left;">Interest form</h3>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Interested</button>
        </form>
        </div>
    {% endif %}
    {% if msg %}
        <h3>{{ msg }}</h3>
    {% endif %}
{% endblock %}

myapp/templates/myapp/products.html
{% extends 'myapp/base.html' %}
{% block title %}Products{% endblock %}
{#{% block myhdg %} Hello The-Four {% endblock %}#}
{% block body_block %}
    {% if prodlist %}
        <h3>Available products from top 10 products in descending order</h3>
        <ol>
            {% for product in prodlist %}
                {% if product.available %}
                    <li><a href="{{ product.id }}/">{{ product.name }}</a></li>
                {% endif %}
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available products!</strong>
    {% endif %}
    <p><a href="{% url 'myapp:placeOrder' %}">Place Order</a></p>
{% endblock %}

myapp/templates/myapp/profile.html
{% extends "myapp/base.html" %}
{% block title %}Profile Page{% endblock title %}
{% block body_block %}
    <div class="row my-3 p-3">
        <img class="rounded-circle account-img" src="{{ user.profile.avatar.url }} " style="cursor: pointer;"/>
    </div>
    {% if user_form.errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <div id="form_errors">
                {% for key, value in user_form.errors.items %}
                    <strong>{{ value }}</strong>
                {% endfor %}
            </div>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    <div class="form-content">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-md-5">
                    <div class="form-group">
                        <label class="small mb-1">Username:</label>
                        {{ user_form.username }}
                        <label class="small mb-1">Email:</label>
                        {{ user_form.email }}
                    </div>
                    <div class="form-group">
                        {#                        <a href="{% url 'password_change' %}">Change Password</a>#}
                        {#                        <hr>#}
                        <label class="small mb-1">Change Avatar:</label>
                        {{ profile_form.avatar }}
                    </div>
                    <label class="small mb-1">Bio:</label> {{ profile_form.bio }}
                </div>
            </div>
            <br><br>
            <button type="submit" class="btn btn-dark btn-lg">Save Changes</button>
            {#            <button type="reset" class="btn btn-dark btn-lg">Reset</button>#}
        </form>
    </div>
{% endblock body_block %}

myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}
{% block title %}Register Page{% endblock %}
{#{% block myhdg %} Hello The-Four {% endblock %}#}
{% block body_block %}
    <div class="form-group">
        <h3 style="text-align: left;">Register</h3>
        <form method="POST">
            {% csrf_token %}
            {{ register_form }}
            <button class="btn btn-primary" type="submit">Register</button>
        </form>
    </div>
{% endblock %}
{% block link_block %}
    <li class="hbar1"><a href="{% url 'myapp:login' %}">Login if already registered</a></li>
    <br/>
{% endblock link_block %}